#!/bin/bash

# Check for proper priveliges
[ "`whoami`" = root ] || exec sudo "$0" "$@"

iptables -t mangle -F
iptables -t filter -F
iptables -t nat -F

iptables -t mangle -P INPUT ACCEPT
iptables -t mangle -P OUTPUT ACCEPT
iptables -t mangle -P FORWARD ACCEPT
iptables -t mangle -P PREROUTING ACCEPT
iptables -t mangle -P POSTROUTING ACCEPT
iptables -t filter -P INPUT DROP
iptables -t filter -P OUTPUT ACCEPT
iptables -t filter -P FORWARD ACCEPT
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT
iptables -t nat -P OUTPUT ACCEPT

iptables -A INPUT -m state --state INVALID -j DROP
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT


# FTP
iptables -A INPUT -p tcp -i eth0 --dport 21 -j ACCEPT
# SSH
iptables -A INPUT -p tcp -i eth0 --dport 22 -j ACCEPT
# HTTP
iptables -A INPUT -p tcp -i eth0 --dport 80 -j ACCEPT
# phpMyAdmin
iptables -A INPUT -p tcp -i eth0 --dport 8866 -j ACCEPT
# SVN
iptables -A INPUT -p tcp -i eth0 --dport 3690 -j ACCEPT
# MySQL
iptables -A INPUT -p tcp -i eth0 --dport 3306 -j ACCEPT
# Allow Ping
iptables -A INPUT -p icmp -i eth0 -j ACCEPT

iptables -L -n -v

iptables-save > /dev/null
